name: socials_app_flutter
description: "A flutter app that can be used to navigate different social medias and platforms"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  async_redux: ^18.0.2
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  get_it: ^7.2.0

  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.6.1
  webview_flutter: ^4.10.0
  pinput: ^5.0.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/